# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: granfalloner@gmail.com
author_name: Myronchuk Vasyl
contract_name: algo_citizens
deployment_language: python
ide_vscode: true
preset_name: starter
project_name: algo_citizens
use_python_black: false
use_python_pytest: false

